name: pickball
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  pin_code_fields: ^8.0.1
  google_nav_bar: ^5.0.7
  line_icons: ^2.0.3
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # ✅ Assets Section
  assets:
    - assets/images/  # ✅ Images Folder
    - assets/fonts/   # ✅ Fonts Folder

  # ✅ Fonts Section (Fixed Path Case Sensitivity)
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf  # ✅ Fixed Path

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-VariableFont.ttf  # ✅ Fixed Path

    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-VariableFont_wght.ttf  # ✅ Fixed Path
